name: improv-living-guide
baseurl: /improv-living-guide
description: improv-living-guide
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0-SNAPSHOT
org: default
markdown: kramdown
